use std::collections::HashSet;

use super::AgentDisplayName;

pub const DEFAULT_AGENT_NAMES: &[&str] = &[
    "Euclid",
    "Archimedes",
    "Ptolemy",
    "Hypatia",
    "Avicenna",
    "Averroes",
    "Aquinas",
    "Copernicus",
    "Kepler",
    "Galileo",
    "Bacon",
    "Descartes",
    "Pascal",
    "Fermat",
    "Huygens",
    "Leibniz",
    "Newton",
    "Halley",
    "Euler",
    "Lagrange",
    "Laplace",
    "Volta",
    "Gauss",
    "Ampere",
    "Faraday",
    "Darwin",
    "Lovelace",
    "Boole",
    "Pasteur",
    "Maxwell",
    "Mendel",
    "Curie",
    "Planck",
    "Tesla",
    "Poincare",
    "Noether",
    "Hilbert",
    "Einstein",
    "Raman",
    "Bohr",
    "Turing",
    "Hubble",
    "Feynman",
    "Franklin",
    "McClintock",
    "Meitner",
    "Herschel",
    "Linnaeus",
    "Wegener",
    "Chandrasekhar",
    "Sagan",
    "Goodall",
    "Carson",
    "Carver",
    "Socrates",
    "Plato",
    "Aristotle",
    "Epicurus",
    "Cicero",
    "Confucius",
    "Mencius",
    "Zeno",
    "Locke",
    "Hume",
    "Kant",
    "Hegel",
    "Kierkegaard",
    "Mill",
    "Nietzsche",
    "Peirce",
    "James",
    "Dewey",
    "Russell",
    "Popper",
    "Sartre",
    "Beauvoir",
    "Arendt",
    "Rawls",
    "Singer",
    "Anscombe",
    "Parfit",
    "Kuhn",
    "Boyle",
    "Hooke",
    "Harvey",
    "Dalton",
    "Ohm",
    "Helmholtz",
    "Gibbs",
    "Lorentz",
    "Schrodinger",
    "Heisenberg",
    "Pauli",
    "Dirac",
    "Bernoulli",
    "Godel",
    "Nash",
    "Banach",
    "Ramanujan",
    "Erdos",
    "Jason",
    "Hokke",
    "Laber",
    "Ada",
    "Knuth",
    "Shannon",
    "Athena",
    "Hermes",
    "Apollo",
    "Atlas",
    "Merlin",
    "Arthur",
    "Wukong",
    "Nezha",
    "Mulan",
    "Orion",
    "Hopper",
    "Artemis",
    "Diana",
    "Minerva",
    "Loki",
    "Freya",
    "Agnesi",
    "Alhazen",
    "Anaxagoras",
    "Anaximander",
    "Apollonius",
    "Aristarchus",
    "Aryabhata",
    "Babbage",
    "Banneker",
    "Bayes",
    "Becquerel",
    "Bell",
    "Bessel",
    "Bhaskara",
    "Bhabha",
    "Blackwell",
    "Boltzmann",
    "Brahe",
    "Brouwer",
    "Burnell",
    "Cajal",
    "Cantor",
    "Cardano",
    "Cartwright",
    "Cassini",
    "Cauchy",
    "Cavendish",
    "Chatelet",
    "Clairaut",
    "Clarke",
    "Clifford",
    "Conway",
    "Crick",
    "Dijkstra",
    "Dobzhansky",
    "Doppler",
    "Edison",
    "Elion",
    "Engelbart",
    "Fibonacci",
    "Fermi",
    "Fleming",
    "Fourier",
    "Frege",
    "Fresnel",
    "Fubini",
    "Galois",
    "Germain",
    "Goldbach",
    "Grothendieck",
    "Hadamard",
    "Hamilton",
    "Hardy",
    "Hawking",
    "Heron",
    "Hertz",
    "Hippocrates",
    "Hodgkin",
    "Jacobi",
    "Jenner",
    "Johnson",
    "Joule",
    "Kalam",
    "Khayyam",
    "Khwarizmi",
    "Kolmogorov",
    "Korolev",
    "Kowalevski",
    "Kruskal",
    "Lamarck",
    "Landau",
    "Lavoisier",
    "Leavitt",
    "Legendre",
    "Lemaitre",
    "Mahalanobis",
    "Marconi",
    "Markov",
    "Maslow",
    "McCarthy",
    "Mendeleev",
    "Mirzakhani",
    "Minkowski",
    "Morse",
    "Moseley",
    "Neumann",
    "Nightingale",
    "Nirenberg",
    "Nobel",
    "Oppenheimer",
    "Onsager",
    "Ostrom",
    "Perelman",
    "Perlmutter",
    "Prigogine",
    "Pythagoras",
    "Quine",
    "Rabi",
    "Riemann",
    "Roentgen",
    "Rogers",
    "Rubin",
    "Rutherford",
    "Salam",
    "Salk",
    "Schawlow",
    "Semmelweis",
    "Shockley",
    "Sklodowska",
    "Smale",
    "Somerville",
    "Spinoza",
    "Stevin",
    "Stokes",
    "Stroustrup",
    "Swartz",
    "Szilard",
    "Tereshkova",
    "Thales",
    "Thompson",
    "Thomson",
    "Torvalds",
    "Tsiolkovsky",
    "Ulam",
    "Vaughan",
    "Veblen",
    "Vesalius",
    "Vieta",
    "Virchow",
    "Wallace",
    "Watson",
    "Weierstrass",
    "Weil",
    "Wiener",
    "Wilkins",
    "Wiles",
    "Witten",
    "Wright",
    "Yang",
    "Yukawa",
    "Zuse",
    "Zwicky",
    "Adele",
    "Alvarez",
    "Anning",
    "Asimov",
    "Atiyah",
    "Bardeen",
    "Bartik",
    "Bearden",
    "Bentham",
    "Binet",
    "Bose",
    "Bragg",
    "Broglie",
    "Cannon",
    "Carnap",
    "Chomsky",
    "Church",
    "Claude",
    "Compton",
    "Condorcet",
    "Courant",
    "Dedekind",
    "DeMorgan",
    "Eddington",
    "Emmy",
    "Eratosthenes",
    "Feigenbaum",
    "Florence",
    "Gamow",
    "GellMann",
    "Grace",
    "Haber",
    "Haldane",
    "Hayek",
    "Hedy",
    "Heraclitus",
    "Hobbes",
    "Huxley",
    "Jevons",
    "Kemeny",
    "Klein",
    "Koch",
    "Lakatos",
    "Lamarr",
    "Langer",
    "Levi",
    "Liskov",
    "Luria",
    "Mach",
    "Maimonides",
    "Margulis",
    "Marr",
    "Mather",
    "Minsky",
    "Montessori",
    "Morgan",
    "Myrdal",
    "Nakamoto",
    "Nambu",
    "Naur",
    "Newcomb",
    "Nozick",
    "Penrose",
    "Phelps",
    "Polya",
    "Post",
    "Radhakrishnan",
    "Resnick",
    "Ritchie",
    "Rosenblueth",
    "Rovelli",
    "Schelling",
    "Shapley",
    "Simon",
    "Skinner",
    "Slipher",
    "Snow",
    "Tao",
    "Tarski",
    "Teller",
    "Tobin",
    "Venter",
    "Voltaire",
    "Waddington",
    "Wald",
    "Weaver",
    "Wheeler",
    "Whittle",
    "Wolfram",
    "Yalow",
    "Yao",
];

#[derive(Debug, Clone, Default)]
pub struct DisplayNamePool {
    next_index: usize,
    assigned: HashSet<String>,
}

impl DisplayNamePool {
    #[must_use]
    pub fn next_name(&mut self) -> AgentDisplayName {
        loop {
            let index = self.next_index;
            self.next_index += 1;
            let candidate = default_agent_name_candidate(index);
            if self.assigned.insert(candidate.clone()) {
                return AgentDisplayName::new(candidate);
            }
        }
    }

    pub fn reserve(&mut self, name: &AgentDisplayName) {
        self.assigned.insert(name.as_str().to_owned());
    }
}

fn default_agent_name_candidate(index: usize) -> String {
    let name_count = DEFAULT_AGENT_NAMES.len();
    if index < name_count {
        return DEFAULT_AGENT_NAMES[index].to_owned();
    }

    let pair_width = name_count - 1;
    let pair_count = name_count * pair_width;
    let pair_index = index - name_count;
    if pair_index < pair_count {
        let first_index = pair_index / pair_width;
        let mut second_index = pair_index % pair_width;
        if second_index >= first_index {
            second_index += 1;
        }
        return format!(
            "{}{}",
            DEFAULT_AGENT_NAMES[first_index], DEFAULT_AGENT_NAMES[second_index]
        );
    }

    let base = DEFAULT_AGENT_NAMES[index % name_count];
    format!("{base}{}", pair_index / pair_count + 2)
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::{DEFAULT_AGENT_NAMES, DisplayNamePool};

    #[test]
    fn default_names_cover_large_swarms_before_numeric_suffixes() {
        assert!(DEFAULT_AGENT_NAMES.len() >= 256);
        assert_eq!(
            DEFAULT_AGENT_NAMES.iter().collect::<HashSet<_>>().len(),
            DEFAULT_AGENT_NAMES.len()
        );

        let mut pool = DisplayNamePool::default();
        let assigned = (0..1024)
            .map(|_| pool.next_name().as_str().to_owned())
            .collect::<Vec<_>>();

        assert_eq!(
            assigned.iter().collect::<HashSet<_>>().len(),
            assigned.len()
        );
        assert!(
            assigned
                .iter()
                .all(|name| !name.chars().last().is_some_and(char::is_numeric))
        );
    }
}
